a=int(input("Enter first number: "))
b=a=int(input("Enter second number: "))
print("The value of",a,"+",3,"is:",a+b)
print("The value of",a,"-",3,"is:",a-b)
print("The value of",a,"/",3,"is:",a/b)
print("The value of",a,"//",3,"is:",a//b)
print("The value of",a,"**",3,"is:",a**b)
print("The value of",a,"%",3,"is:",a%b)